[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bwserver = { path = "../bwserver", feature = "full" }
procmacro = { path = "../procmacro", feature = "full" }
log = "0.4.17"
proc-macro3 = "0.1.1"
